/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProductsRouteImport } from './routes/_products'
import { Route as ProductsIndexRouteImport } from './routes/_products/index'
import { Route as ProductsOrderSuccessRouteImport } from './routes/_products/order-success'
import { Route as ProductsCheckoutRouteImport } from './routes/_products/checkout'
import { Route as ProductsCartRouteImport } from './routes/_products/cart'
import { Route as ProductsProductSlugRouteImport } from './routes/_products/$productSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/_products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsOrderSuccessRoute = ProductsOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCheckoutRoute = ProductsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCartRoute = ProductsCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$productSlug': typeof ProductsProductSlugRoute
  '/cart': typeof ProductsCartRoute
  '/checkout': typeof ProductsCheckoutRoute
  '/order-success': typeof ProductsOrderSuccessRoute
  '/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$productSlug': typeof ProductsProductSlugRoute
  '/cart': typeof ProductsCartRoute
  '/checkout': typeof ProductsCheckoutRoute
  '/order-success': typeof ProductsOrderSuccessRoute
  '/': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_products': typeof ProductsRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_products/$productSlug': typeof ProductsProductSlugRoute
  '/_products/cart': typeof ProductsCartRoute
  '/_products/checkout': typeof ProductsCheckoutRoute
  '/_products/order-success': typeof ProductsOrderSuccessRoute
  '/_products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/$productSlug'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/register'
    | '/$productSlug'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/'
  id:
    | '__root__'
    | '/_products'
    | '/admin'
    | '/login'
    | '/register'
    | '/_products/$productSlug'
    | '/_products/cart'
    | '/_products/checkout'
    | '/_products/order-success'
    | '/_products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProductsRoute: typeof ProductsRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_products': {
      id: '/_products'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_products/': {
      id: '/_products/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_products/order-success': {
      id: '/_products/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof ProductsOrderSuccessRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_products/checkout': {
      id: '/_products/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ProductsCheckoutRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_products/cart': {
      id: '/_products/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ProductsCartRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_products/$productSlug': {
      id: '/_products/$productSlug'
      path: '/$productSlug'
      fullPath: '/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ProductsCartRoute: typeof ProductsCartRoute
  ProductsCheckoutRoute: typeof ProductsCheckoutRoute
  ProductsOrderSuccessRoute: typeof ProductsOrderSuccessRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsCartRoute: ProductsCartRoute,
  ProductsCheckoutRoute: ProductsCheckoutRoute,
  ProductsOrderSuccessRoute: ProductsOrderSuccessRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProductsRoute: ProductsRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
